name: 🧪

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 1"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
      - run: pip install .[test] pytest-xdist
        name: Install
      - run: python3 -m pytest -n=auto --durations=50 test -W error
        name: Run unit tests
      - run: python3 -m pytest demo/test_demos.py -W error
        name: Run demos

  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - uses: actions/checkout@v4
      - run: python3 -m pip install -e .[style,docs]
      - run: |
          python3 -m ruff check .
          python3 -m ruff format --check .
        name: Run ruff checks
      - run: python3 -m mypy .
        name: Run mypy checks
      - run: |
          cd docs
          make html SPHINXOPTS="-W"
        name: Test docs build
